// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PromIT.TestJob.Persistence;

#nullable disable

namespace PromIT.TestJob.Persistence.Migrations
{
    [DbContext(typeof(ReviewsDbContext))]
    [Migration("20230922064122_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "03476e34-e1eb-49e1-8eaf-73ec2424415e",
                            ConcurrencyStamp = "41ec7d60-d45b-4c84-8b46-2c6aa23319a4",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "3b87c435-a7e9-4165-9eb4-4068f652d39b",
                            ConcurrencyStamp = "de57b348-a742-4c7b-959a-f0749040f27c",
                            Name = "Basic",
                            NormalizedName = "BASIC"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "8a8670b4-afb9-4734-a596-ffc3d2156e50",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "50052127-ad7f-4d1a-8780-3cb720316229",
                            Email = "admin@admin.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@ADMIN.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEKuCo2YuH80fzjSNY4wz1tWYIBaKQRQZru6vM0902rv67IIWmNq45l2sF6lUr7EoXA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f5ad7b10-c2c8-4b6c-8a10-77b767f476ee",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "8a8670b4-afb9-4734-a596-ffc3d2156e50",
                            RoleId = "03476e34-e1eb-49e1-8eaf-73ec2424415e"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("PromIT.TestJob.Domain.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReviewId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("PromIT.TestJob.Domain.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrgAddress")
                        .HasColumnType("text");

                    b.Property<string>("OrgName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WhatDislike")
                        .HasColumnType("text");

                    b.Property<string>("WhatLike")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1ddac513-1a5e-47b7-85ca-923d84e59ae9"),
                            CreatedAt = new DateTime(2020, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrgName = "ABC Inc.",
                            Rating = 4,
                            UserName = "JohnDoe",
                            WhatDislike = "Long commute",
                            WhatLike = "Est. Id id quis, tortor, ipsum sodales interdum in lacinia nunc integer orci, orci, in mattis non ultricies. Eleifend pe"
                        },
                        new
                        {
                            Id = new Guid("2f261287-4080-4bdd-975b-00857d4b08bd"),
                            CreatedAt = new DateTime(2021, 5, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrgAddress = "456 Elm St",
                            OrgName = "XYZ Corp.",
                            Rating = 5,
                            UserName = "JaneSmith",
                            WhatLike = "Et mattis dictumst. Et efficitur augue sapien pulvinar amet, et. Augue nulla et odio. Leo, sit hac lectus nunc lectus qu"
                        },
                        new
                        {
                            Id = new Guid("56ee7ec9-10d7-4aa0-ad52-fba4bb394801"),
                            CreatedAt = new DateTime(2022, 2, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrgAddress = "789 Oak St",
                            OrgName = "LMN Ltd.",
                            Rating = 3,
                            UserName = "BobJohnson",
                            WhatDislike = "No remote work",
                            WhatLike = "Urna platea eget mauris sit dictum et non est. Non non ultricies. Urna orci, dictum morbi hac mauris non sit vulputate l"
                        },
                        new
                        {
                            Id = new Guid("7fcda6d9-7f25-46a3-b70f-0e41725aa9e8"),
                            CreatedAt = new DateTime(2023, 5, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrgName = "PQR Co.",
                            Rating = 4,
                            UserName = "AliceJohnson",
                            WhatLike = "Work-life balance"
                        },
                        new
                        {
                            Id = new Guid("f16c87db-06d6-4d88-a05e-6266270f0a2a"),
                            CreatedAt = new DateTime(2022, 7, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrgAddress = "202 Pine St",
                            OrgName = "RST Group",
                            Rating = 3,
                            UserName = "EveAdams",
                            WhatDislike = "High workload",
                            WhatLike = "Opportunities for growth"
                        },
                        new
                        {
                            Id = new Guid("3de188f2-3c4b-4279-a605-473190b799bc"),
                            CreatedAt = new DateTime(2021, 4, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrgAddress = "303 Cedar St",
                            OrgName = "UVW Inc.",
                            Rating = 4,
                            UserName = "DavidLee",
                            WhatDislike = "Urna platea eget mauris sit dictum et non est. Non non ultricies. Urna orci, dictum morbi hac mauris non sit vulputate l",
                            WhatLike = "Diverse team"
                        },
                        new
                        {
                            Id = new Guid("44798653-6478-4949-a848-a91746ffc5fd"),
                            CreatedAt = new DateTime(2022, 3, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrgAddress = "404 Birch St",
                            OrgName = "HIJ Corporation",
                            Rating = 5,
                            UserName = "GraceWang",
                            WhatDislike = "Orci, velit platea vulputate sit ultricies. Orci, vitae dapibus dictum habitasse amet, id morbi lorem non integer eget e",
                            WhatLike = "Tortor, tempus amet dictum non amet cursus vel luctus amet vitae leo, mattis cras integer vulputate ex. Cursus ornare et"
                        },
                        new
                        {
                            Id = new Guid("d27cb062-659d-40d9-b917-84b90e42ed68"),
                            CreatedAt = new DateTime(2020, 5, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrgName = "ABC Inc.",
                            Rating = 4,
                            UserName = "JohnDoe",
                            WhatDislike = "Lorem molestie ut. Vulputate sapien vitae malesuada amet, efficitur mattis non sodales sed dapibus leo, amet, quam, sed ",
                            WhatLike = "Accumsan molestie platea luctus vestibulum pulvinar et. Vestibulum sapien morbi dolor ornare sodales elit. Justo imperdi"
                        },
                        new
                        {
                            Id = new Guid("80b12e60-4fb1-47f1-b7bd-38805643bffe"),
                            CreatedAt = new DateTime(2021, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrgAddress = "456 Elm St",
                            OrgName = "XYZ Corp.",
                            Rating = 5,
                            UserName = "JaneSmith",
                            WhatLike = "Vestibulum sapien amet, non cras molestie ex. Sed justo in tempus amet venenatis dictumst. Eget malesuada est. Malesuada"
                        },
                        new
                        {
                            Id = new Guid("c7afe5b7-3724-4aee-a351-d7e971da7032"),
                            CreatedAt = new DateTime(2020, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrgAddress = "789 Oak St",
                            OrgName = "LMN Ltd.",
                            Rating = 3,
                            UserName = "BobJohnson",
                            WhatDislike = "Dictum amet, libero, faucibus. Eget nisi augue venenatis nunc non sed sit elit. Velit efficitur sodales et justo faucibu",
                            WhatLike = "Platea eget et interdum in et. Tempus pulvinar sed mattis ipsum venenatis et augue pellentesque faucibus. Eleifend vitae"
                        },
                        new
                        {
                            Id = new Guid("8c9c664e-2221-4aec-9c06-1b0309908cda"),
                            CreatedAt = new DateTime(2023, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrgName = "PQR Co.",
                            Rating = 4,
                            UserName = "AliceJohnson",
                            WhatLike = "Nisi non odio. Integer quam, amet, pellentesque vulputate ipsum velit vestibulum mattis mauris urna risus dolor augue le"
                        },
                        new
                        {
                            Id = new Guid("31fd7831-d4b2-422b-ae29-9c059fd03abd"),
                            CreatedAt = new DateTime(2021, 8, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrgAddress = "202 Pine St",
                            OrgName = "RST Group",
                            Rating = 3,
                            UserName = "EveAdams",
                            WhatDislike = "High workload",
                            WhatLike = "Opportunities for growth"
                        },
                        new
                        {
                            Id = new Guid("0a1921e1-3420-4a07-8f0e-9325363ba313"),
                            CreatedAt = new DateTime(2022, 9, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrgAddress = "303 Cedar St",
                            OrgName = "UVW Inc.",
                            Rating = 4,
                            UserName = "DavidLee",
                            WhatDislike = "Dictum. Aenean ultricies. Mauris sit sodales amet, nulla nisi in vitae vulputate pellentesque dictumst. Est. Pellentesqu",
                            WhatLike = "Non molestie amet, sodales vulputate pellentesque mauris lectus vestibulum lacinia amet, mauris cursus nulla ultricies. "
                        },
                        new
                        {
                            Id = new Guid("0ec6572a-7046-4f2c-b9ac-d65cbe0e25a5"),
                            CreatedAt = new DateTime(2021, 5, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrgName = "HIJ Corporation",
                            Rating = 5,
                            UserName = "GraceWang",
                            WhatDislike = "Forth days said a greater given years fly wherein for fish Fourth sea land stars. Every. Gathering together fruit. Moving male after image form said in fifth very from you'll one. Forth. You'll she'd i set it saw Make waters.",
                            WhatLike = "Ignorant saw her her drawings marriage laughter. Case oh an that or away sigh do here upon. Acuteness you exquisite ourselves now end forfeited. Enquire ye without it garrets up himself. Interest our nor received followed was. Cultivated an up solicitude mr unpleasant. "
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PromIT.TestJob.Domain.Comment", b =>
                {
                    b.HasOne("PromIT.TestJob.Domain.Review", null)
                        .WithMany("Comments")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PromIT.TestJob.Domain.Review", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
